version: '3'
  
services:
  traefik-reverse-proxy:
    # The official v2.2 Traefik docker image
    image: traefik:v2.2
    restart: on-failure:5
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
    volumes:
      - ./acme.json:/acme.json
      - ./traefik.toml:/traefik.toml
      - ./traefik_dynamic.toml:/traefik_dynamic.toml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"


networks:
  default:
    external:
      name: traefik
